#!/bin/bash
set -eu

rm -f /etc/motd
sed -i 's/#NAutoVTs=.*/NAutoVTs=4/' /etc/systemd/logind.conf
sed -i 's/TTYVTDisallocate=.*/TTYVTDisallocate=no/' '/usr/lib/systemd/system/getty@.service'
sed -i 's/ExecStart=.*/ExecStart=\/sbin\/agetty --autologin root --login-pause --noclear %I $TERM/' '/usr/lib/systemd/system/getty@.service'
