#!/bin/bash
set -eu

# Install the latest Docker
apt-get install --no-install-recommends --yes \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg2 \
    software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) stable"
apt-get update
apt-get install --no-install-recommends --yes \
    docker-ce docker-ce-cli containerd.io
dpkg --force-all --purge \
    apt-transport-https \
    gnupg2 \
    software-properties-common
