#!/bin/bash
set -eu

# Unnecesary packages
apt-get remove --purge --yes \
	apt-utils \
	aptitude \
	dselect \
	info \
	man-db \
	manpages \
	wget
apt-get autoremove --yes || true
dpkg --force-all --purge \
	apt \
	busybox \
	debconf-i18n \
	debian-archive-keyring \
	cpio \
	gcc-4.8-base:amd64 \
	gcc-4.9-base:amd64 \
	ibuuid-perl \
	initramfs-tools \
	file \
	klibc-utils \
	libklibc \
	live-tools \
	libtext-wrapi18n-perl \
	libtext-charwidth-perl \
	liblocale-gettext-perl l\
	libtext-iconv-perl \
	openssl

# Unnecesary files
find . -name *~ | xargs rm -f
rm -rf /usr/include/*
rm -rf /usr/share/doc/*
rm -rf /usr/share/locale/*
rm -rf /usr/share/man/*
rm -rf /usr/share/i18n/*
rm -rf /usr/share/info/*
rm -rf /usr/share/lintian/*
rm -rf /usr/share/linda/*
rm -rf /usr/share/zoneinfo/*
rm -rf /var/cache/man/*
rm -f /usr/bin/omshell
rm -f /var/cache/debconf/templates.dat
rm -f /var/cache/debconf/templates.dat-old
rm -f /usr/bin/openssl
rm -f /usr/sbin/visudo
rm -f /usr/bin/oldfind
rm -rf /usr/share/mime/*
rm -rf /usr/share/X11/*
rm -rf /usr/share/fonts/*
rm -f /var/lib/dpkg/info/linux-image*-amd64.md5sums
rm -f /var/lib/apt/lists/*
rm -rf /usr/share/file
rm -rf /usr/share/zoneinfo
rm -rf /var/lib/dpkg
rm -rf /usr/lib/locale
rm -f /usr/bin/gpg
rm -f /usr/bin/gpgv
rm -f /sbin/ldconfig.real
rm -rf /usr/lib/x86_64-linux-gnu/gconv
rm -rf /usr/lib/x86_64-linux-gnu/libdb*.so
rm -rf /usr/lib/x86_64-linux-gnu/libapt*.so.*
rm -rf /usr/lib/x86_64-linux-gnu/libapt*.so
rm -rf /usr/lib/libperl*.so*
rm -rf /lib/modules/3.13-1-amd64/modules.alias
rm -rf /usr/lib/apt
rm -rf /var/lib/initramfs-tools
rm -rf /usr/share/perl
rm -rf /usr/bin/dpkg*
echo "" > /etc/resolv.conf
rm -rf /tmp/*

# Kernel modules
rm -rf /lib/modules/*/kernel/sound/*
rm -rf /lib/modules/*/kernel/drivers/gpu/*
rm -rf /lib/modules/*/kernel/drivers/isdn/*
rm -rf /lib/modules/*/kernel/drivers/media/*
rm -rf /lib/modules/*/kernel/drivers/staging/media/*
rm -rf /lib/modules/*/kernel/drivers/staging/lustre/*
rm -rf /lib/modules/*/kernel/drivers/staging/comedi/*
rm -rf /lib/modules/*/kernel/drivers/staging/rtl8192e/*
rm -rf /lib/modules/*/kernel/drivers/staging/rtl8192u/*
rm -rf /lib/modules/*/kernel/drivers/staging/rtl8187se/*
rm -rf /lib/modules/*/kernel/drivers/staging/rtl8712/*
rm -rf /lib/modules/*/kernel/drivers/staging/speakup/*
rm -rf /lib/modules/*/kernel/fs/ocfs2/*
rm -rf /lib/modules/*/kernel/fs/ntfs/*
rm -rf /lib/modules/*/kernel/fs/ubifs/*
rm -rf /lib/modules/*/kernel/fs/reiserfs/*
rm -rf /lib/modules/*/kernel/fs/jffs2/*
rm -rf /lib/modules/*/kernel/fs/hfsplus/*
rm -rf /lib/modules/*/kernel/fs/gfs2/*
rm -rf /lib/modules/*/kernel/drivers/net/mac80211/*
rm -rf /lib/modules/*/kernel/drivers/net/wireless/*
rm -rf /lib/modules/*/kernel/drivers/net/wimax/*
rm -rf /lib/modules/*/kernel/drivers/net/irda/*
rm -rf /lib/modules/*/kernel/drivers/net/hamradio/*
rm -rf /lib/modules/*/kernel/drivers/net/arcnet/*
rm -rf /lib/modules/*/kernel/drivers/net/can/*
rm -rf /lib/modules/*/kernel/drivers/net/ethernet/qlogic/*
rm -rf /lib/modules/*/kernel/drivers/scsi/bfa/*
rm -rf /lib/modules/*/kernel/arch/x86/kvm/*
rm -rf /lib/modules/*/kernel/net/wireless/*
rm -rf /lib/modules/*/kernel/net/mac80211/*
rm -rf /lib/modules/*/kernel/net/sunrpc/*
rm -rf /lib/modules/*/kernel/net/bluetooth/*
rm -rf /lib/modules/*/kernel/net/irda/*

for i in $(ls /lib/modules/);
do
depmod $i
done

# Truncate logs
for FILE in $(find /var/log/ -type f)
do
	: > ${FILE}
done

